package main

import (
	"fmt"
	"strings"
	"unicode"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	"gitcode.com/protocgenplugin/protoc-gen-go-api-errors/apierror"
)

const (
	// errorsPackage = protogen.GoImportPath("gitcode.com/protocgenplugin/protoc-gen-go-api-errors/apierror")
	fmtPackage    = protogen.GoImportPath("fmt")
)

var enCases = cases.Title(language.AmericanEnglish, cases.NoLower)

// generateFile generates a _errors.pb.go file containing kratos errors definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Enums) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_errors.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-api-errors. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.QualifiedGoIdent(fmtPackage.Ident(""))
	generateFileContent(gen, file, g)
	return g
}

// generateFileContent generates the api errors definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Enums) == 0 {
		return
	}

	// g.P("// This is a compile-time assertion to ensure that this generated file")
	// g.P("// is compatible with the kratos package it is being compiled against.")
	// g.P("const _ = ", errorsPackage.Ident("SupportPackageIsVersion1"))
	g.P()
	index := 0
	for _, enum := range file.Enums {
		if !genErrorsReason(gen, file, g, enum) {
			index++
		}
	}
	// If all enums do not contain 'errors.code', the current file is skipped
	if index == 0 {
		g.Skip()
	}
}

func genErrorsReason(_ *protogen.Plugin, _ *protogen.File, g *protogen.GeneratedFile, enum *protogen.Enum) bool {
	var defaultStatusCode int32
	if code, ok := proto.GetExtension(enum.Desc.Options(), apierror.E_DefaultStatusCode).(int32); ok && code > 0 {
		defaultStatusCode = code
	}
	var defaultCode int32
	if code, ok := proto.GetExtension(enum.Desc.Options(), apierror.E_DefaultCode).(int32); ok && code > 0 {
		defaultCode = code
	}
	var wrapper errorWrapper
	for _, enumValue := range enum.Values {
		valueStatusCode := defaultStatusCode
		if code, ok := proto.GetExtension(enumValue.Desc.Options(), apierror.E_StatusCode).(int32); ok && code > 0 {
			valueStatusCode = code
		} else {
			valueStatusCode = defaultStatusCode
		}
		valueCode := defaultCode
		if code, ok := proto.GetExtension(enumValue.Desc.Options(), apierror.E_Code).(int32); ok && code > 0 {
			valueCode = code
		} else {
			valueCode = defaultCode
		}
		println(fmt.Sprintf("valueStatusCode: %d, valueCode: %d", valueStatusCode, valueCode))
		if valueStatusCode <= 0 && valueCode <= 0 {
			continue
		}

		comment := enumValue.Comments.Leading.String()
		if comment == "" {
			comment = enumValue.Comments.Trailing.String()
		}

		err := &errorInfo{
			Name:       string(enum.Desc.Name()),
			Value:      string(enumValue.Desc.Name()),
			CamelValue: case2Camel(string(enumValue.Desc.Name())),
			StatusCode: valueStatusCode,
			Code:       valueCode,
			Comment:    comment,
			HasComment: len(comment) > 0,
		}
		wrapper.Errors = append(wrapper.Errors, err)
	}
	if len(wrapper.Errors) == 0 {
		return true
	}
	g.P(wrapper.execute())

	return false
}

func case2Camel(name string) string {
	if !strings.Contains(name, "_") {
		if name == strings.ToUpper(name) {
			name = strings.ToLower(name)
		}
		return enCases.String(name)
	}
	strs := strings.Split(name, "_")
	words := make([]string, 0, len(strs))
	for _, w := range strs {
		hasLower := false
		for _, r := range w {
			if unicode.IsLower(r) {
				hasLower = true
				break
			}
		}
		if !hasLower {
			w = strings.ToLower(w)
		}
		w = enCases.String(w)
		words = append(words, w)
	}

	return strings.Join(words, "")
}
