// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apierror.proto

package apierror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_apierror_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1106,
		Name:          "errors.default_status_code",
		Tag:           "varint,1106,opt,name=default_status_code",
		Filename:      "apierror.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1108,
		Name:          "errors.default_code",
		Tag:           "varint,1108,opt,name=default_code",
		Filename:      "apierror.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1107,
		Name:          "errors.status_code",
		Tag:           "varint,1107,opt,name=status_code",
		Filename:      "apierror.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1109,
		Name:          "errors.code",
		Tag:           "varint,1109,opt,name=code",
		Filename:      "apierror.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional int32 default_status_code = 1106;
	E_DefaultStatusCode = &file_apierror_proto_extTypes[0]
	// optional int32 default_code = 1108;
	E_DefaultCode = &file_apierror_proto_extTypes[1]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional int32 status_code = 1107;
	E_StatusCode = &file_apierror_proto_extTypes[2]
	// optional int32 code = 1109;
	E_Code = &file_apierror_proto_extTypes[3]
)

var File_apierror_proto protoreflect.FileDescriptor

const file_apierror_proto_rawDesc = "" +
	"\n" +
	"\x0eapierror.proto\x12\x06errors\x1a google/protobuf/descriptor.proto:M\n" +
	"\x13default_status_code\x12\x1c.google.protobuf.EnumOptions\x18\xd2\b \x01(\x05R\x11defaultStatusCode:@\n" +
	"\fdefault_code\x12\x1c.google.protobuf.EnumOptions\x18\xd4\b \x01(\x05R\vdefaultCode:C\n" +
	"\vstatus_code\x12!.google.protobuf.EnumValueOptions\x18\xd3\b \x01(\x05R\n" +
	"statusCode:6\n" +
	"\x04code\x12!.google.protobuf.EnumValueOptions\x18\xd5\b \x01(\x05R\x04codeB_\n" +
	"4com.gitcode.protocgenplugin.protoc_gen_go_api_errorsP\x01Z\x1aapierror/apierror;apierror\xa2\x02\bAPIErrorb\x06proto3"

var file_apierror_proto_goTypes = []any{
	(*descriptorpb.EnumOptions)(nil),      // 0: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_apierror_proto_depIdxs = []int32{
	0, // 0: errors.default_status_code:extendee -> google.protobuf.EnumOptions
	0, // 1: errors.default_code:extendee -> google.protobuf.EnumOptions
	1, // 2: errors.status_code:extendee -> google.protobuf.EnumValueOptions
	1, // 3: errors.code:extendee -> google.protobuf.EnumValueOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apierror_proto_init() }
func file_apierror_proto_init() {
	if File_apierror_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apierror_proto_rawDesc), len(file_apierror_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_apierror_proto_goTypes,
		DependencyIndexes: file_apierror_proto_depIdxs,
		ExtensionInfos:    file_apierror_proto_extTypes,
	}.Build()
	File_apierror_proto = out.File
	file_apierror_proto_goTypes = nil
	file_apierror_proto_depIdxs = nil
}
